name: Build and deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.30/mdbook-v0.4.30-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          bin/mdbook build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: book
