name: Build and deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: XAMPPRocky/deploy-mdbook@v1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
